config/routes.rb
Hm::Application.routes.draw do
  resources :parents
  resources :sessions, only: [:new, :create, :destroy]
  resources :challenges, controller: "resources", type: "Challenge"
  resources :rewards, controller: "resources", type: "Reward"
  resources :children
  resources :assigned_challenges
  resources :enabled_rewards
  resources :messages
  resources :categories, only: [:index]

  root to: 'static_pages#home'

  match '/signup',   to: 'parents#new'
  match '/signin',   to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy', via: :delete

  match '/about',                   to: 'static_pages#about'
  match '/legal',                   to: 'static_pages#legal'
  match '/partners',                to: 'static_pages#partners'
  match '/how_it_works',            to: 'static_pages#how_it_works'
  match '/parent_child_connection', to: 'static_pages#parent_child_connection'
  match '/community',               to: 'static_pages#community'
  match '/glossary_of_terms',       to: 'static_pages#glossary_of_terms'
  match '/challenge_categories',    to: 'static_pages#challenge_categories'
  
  match '/challenges_your',           to: 'challenges#your'
  match '/challenges_community_pool', to: 'challenges#community_pool'
  match '/rewards_your',              to: 'rewards#your'
  match '/rewards_community_pool',    to: 'rewards#community_pool'
  match '/children_your',             to: 'children#your'
  match '/parent_dash',               to: 'parents#dash'
  match '/completed_challenges',      to: 'assigned_challenges#completed'
  match '/child_dash',                to: 'children#dash'

  match '/contact' => 'contact#new', :as => 'contact', :via => :get
  match '/contact' => 'contact#create', :as => 'contact', :via => :post

  match '/report_abuse' => 'report_abuse#new', :as => 'report_abuse', :via => :get
  match '/report_abuse' => 'report_abuse#create', :as => 'report_abuse', :via => :post

end

app/models/reward.rb
# == Schema Information
#
# Table name: resources
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  public      :boolean
#  parent_id   :integer
#  type        :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#

class Reward < Resource
  has_many :enabled_rewards
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  def community_pool
    @community_pool = Reward.where(type: "Reward")

    respond_to do |format|
      format.html
      format.json { render json: @community_pool }
    end
  end

  def your
    @your_rewards = current_user.rewards
  end
end

app/views/rewards/community_pool.html.erb
<div id="par_content">
  <div id="avatarbase_contact">
    <div id="right_avatar_commpool"><img src="assets/avatars/cowboy.png" alt="cowboy" /></div>
  </div><!--end #avatarbase-->

  <p align="center"><img src="assets/Community-Pool-Bar_01.png" alt="Action Items" width="872" height="28" /></p>

  <div align="center"><br />
    <div ng-app="rewards">
      <div ng-controller="RewardsCommunityPoolCtrl">
        Search:
        <input ng-model="search">      

        Items per page:
        <select ng-model="items_per_page">
          <option value="5">5</option>
          <option value="10">10</option>
          <option value="25">25</option>
          <option value="50">50</option>
          <option value="100">100</option>
          <option value="200">200</option>
        </select>

        <table width="824" border="0" cellspacing="5" cellpadding="10" >
          <tr>
            <td width="794"  align="left" valign="top">
              <span class="par_mod_header">
                Rewards Available: <%= Reward.count(:all) %>
              </span>
              <hr color="#e99723" align="left" width="95%"/>
            </td>
          </tr>

          <table width="461" border="0" cellspacing="3" cellpadding="0">
            <tbody ng-repeat="reward in rewards | filter:search | orderBy:'-updated_at' | limitTo:items_per_page" >
              <tr>
                <td width="400">{{reward.name}}</td>
                <td wdith="27">
                  <a ng-href="enabled_rewards/new?enabled_reward%5Breward_id%5D={{reward.id}}">
                    <img src="assets/check.png" alt="report abuse" width="17" height="17" />
                  </a>
                </td>
                <td width="27">
                  <a ng-href="report_abuse?message%5Bsubject%5D=Report+Abuse+-+{{reward.name}}+({{reward.id}})">
                    <img src="assets/redflag.png" alt="report abuse" width="17" height="17" />
                  </a>
                </td>
              </tr>
            </tbody>
          </table>
        </table>
      </div>
    </div>
  </div>
  <p align="center">&nbsp;</p>
  <p align="center">&nbsp;</p>
</div><!--end #feature-->
</div> <!--end #wrap-->

<div id="spacer" ></div> <!--end #spacer-->

</body>
</html>

app/views/rewards/community_pool_old.html.erb
<% provide(:title, "Rewards Community Pool") %>
<h1>Rewards Community Pool</h1>

<%= form_tag rewards_community_pool_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<ol>
  <% @rewards.each do |reward| %>
    <li><%= reward.name %></li>
  <% end %>
</ol>
<br>
<%= link_to "Enable a reward", new_enabled_reward_path %>

app/views/rewards/new.html.erb
<% provide(:title, 'Create a Reward') %>
<h1>Create a Reward</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@reward) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.label :public, "Public?" %>
      <%= f.check_box :public %>

      <%= f.submit "Create Reward", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/rewards/your.html.erb
<% provide(:title, "Your") %>
<h1>Your rewards</h1>
<ol>
  <% @your_rewards.each do |reward| %>
    <li><%= reward.name %></li>
  <% end %>
</ol>