config/routes.rb
Hm::Application.routes.draw do
  resources :parents
  resources :sessions, only: [:new, :create, :destroy]
  resources :challenges, controller: "resources", type: "Challenge"
  resources :rewards, controller: "resources", type: "Reward"
  resources :children
  resources :assigned_challenges
  resources :enabled_rewards
  resources :messages
  resources :categories, only: [:index]

  root to: 'static_pages#home'

  match '/signup',   to: 'parents#new'
  match '/signin',   to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy', via: :delete

  match '/about',                   to: 'static_pages#about'
  match '/legal',                   to: 'static_pages#legal'
  match '/partners',                to: 'static_pages#partners'
  match '/how_it_works',            to: 'static_pages#how_it_works'
  match '/parent_child_connection', to: 'static_pages#parent_child_connection'
  match '/community',               to: 'static_pages#community'
  match '/glossary_of_terms',       to: 'static_pages#glossary_of_terms'
  match '/challenge_categories',    to: 'static_pages#challenge_categories'
  
  match '/challenges_your',           to: 'challenges#your'
  match '/challenges_community_pool', to: 'challenges#community_pool'
  match '/rewards_your',              to: 'rewards#your'
  match '/rewards_community_pool',    to: 'rewards#community_pool'
  match '/children_your',             to: 'children#your'
  match '/parent_dash',               to: 'parents#dash'
  match '/completed_challenges',      to: 'assigned_challenges#completed'
  match '/child_dash',                to: 'children#dash'

  match '/contact' => 'contact#new', :as => 'contact', :via => :get
  match '/contact' => 'contact#create', :as => 'contact', :via => :post

  match '/report_abuse' => 'report_abuse#new', :as => 'report_abuse', :via => :get
  match '/report_abuse' => 'report_abuse#create', :as => 'report_abuse', :via => :post

end

app/controllers/report_abuse_controller.rb
class ReportAbuseController < ApplicationController
  def new
    @message = Message.new(params[:message])
    @message.email = current_user.email
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.report_abuse_message(@message).deliver
      flash[:success] = "Message was successfully sent."
      redirect_to parent_dash_path
    else
      flash[:error] = "Please fill all fields."
      redirect_to :back
    end
  end

end

app/views/report_abuse/new.html.erb
<div id="content">

<div id="avatarbase_contact">
  <div id="left_img_contact"><%= image_tag("avatars/ninjagirl_rt2.png", alt: "Ninja Girl") %></div>
</div><!--end #avatarbase-->

<div id="forty_left" class="align_lt">
 <%= form_for @message, :url => report_abuse_path do |f| %>
    <h1>Report Abuse</h1>
    <p>&nbsp;</p>
    <div align="center">
      <table width="auto" border="0" cellspacing="12" cellpadding="0" id="reg_table">
        <tr class="rowheight">
          <td width="135" height="40" class="labels">First Name:</td>
            <td width="278" height="40" class="fields"><%= f.text_field :first_name %></td>
            <td width="155" class="labels">Last Name:</td>
            <td width="242" class="fields"><%= f.text_field :last_name %></td>
          </tr>
        <tr class="rowheight", size="40">
          <td class="labels" height="40">Email:</td>
            <td class="fields"><%= f.text_field :email, readonly: true %></td>
            <td class="labels">&nbsp;</td>
            <td class="fields">&nbsp;</td>
          </tr>
          <tr class="rowheight", size="40">
          <td class="labels" height="40">Subject:</td>
            <td class="fields"><%= f.text_field :subject, readonly: true, size: "70" %></td>
            <td class="labels">&nbsp;</td>
            <td class="fields">&nbsp;</td>
          </tr>
        <tr class="rowheight">
          <td class="labels" height="40" valign="top"><p>Comment/Question(s):</p>
            </td>
            <td colspan="3" class="fields"><p>
              <%= f.text_area :body, :size => "70x5" %>
              </p>
            </td>
        </tr>
        <tr class="rowheight">
          <td colspan="4" class="labels"><div align="center">            <br />
            <%= f.submit :type => :image, :src => "/assets/send.png" %>
          </div></td>
          </tr>
      </table>
    </div>
 <% end %>

 <p>
  <!--end #forty_left-->
  <%= image_tag("spacer.gif", height: "150px") %></p>
 <p>&nbsp;</p>
 <p>&nbsp;</p>
 <p>&nbsp;</p>
 <p>&nbsp; </p>
</div> <!--end #content-->