config/routes.rb
Hm::Application.routes.draw do
  resources :parents
  resources :sessions, only: [:new, :create, :destroy]
  resources :challenges, controller: "resources", type: "Challenge"
  resources :rewards, controller: "resources", type: "Reward"
  resources :children
  resources :assigned_challenges
  resources :enabled_rewards
  resources :messages
  resources :categories, only: [:index]

  root to: 'static_pages#home'

  match '/signup',   to: 'parents#new'
  match '/signin',   to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy', via: :delete

  match '/about',                   to: 'static_pages#about'
  match '/legal',                   to: 'static_pages#legal'
  match '/partners',                to: 'static_pages#partners'
  match '/how_it_works',            to: 'static_pages#how_it_works'
  match '/parent_child_connection', to: 'static_pages#parent_child_connection'
  match '/community',               to: 'static_pages#community'
  match '/glossary_of_terms',       to: 'static_pages#glossary_of_terms'
  match '/challenge_categories',    to: 'static_pages#challenge_categories'
  
  match '/challenges_your',           to: 'challenges#your'
  match '/challenges_community_pool', to: 'challenges#community_pool'
  match '/rewards_your',              to: 'rewards#your'
  match '/rewards_community_pool',    to: 'rewards#community_pool'
  match '/children_your',             to: 'children#your'
  match '/parent_dash',               to: 'parents#dash'
  match '/completed_challenges',      to: 'assigned_challenges#completed'
  match '/child_dash',                to: 'children#dash'

  match '/contact' => 'contact#new', :as => 'contact', :via => :get
  match '/contact' => 'contact#create', :as => 'contact', :via => :post

  match '/report_abuse' => 'report_abuse#new', :as => 'report_abuse', :via => :get
  match '/report_abuse' => 'report_abuse#create', :as => 'report_abuse', :via => :post

end

app/models/parent.rb
# == Schema Information
#
# Table name: parents
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean          default(FALSE)
#

class Parent < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation, :admin
  has_secure_password
  has_many :challenges
  has_many :rewards
  has_many :children
  has_many :assigned_challenges
  has_many :enabled_rewards


  before_save { |parent| parent.email = email.downcase }
  before_save :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  VALID_PASSWORD_REGEX = /(?=.{6,})^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[\!\@\#\$\%\^\&\*\-]).*$/
  validates :password, presence: true, length: { minimum: 6 }, format: { with: VALID_PASSWORD_REGEX }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_filter :signed_in_parent, only: [:index, :edit, :update, :destroy]
  before_filter :correct_parent, only: [:edit, :update]
  before_filter :admin_parent, only: :destroy

  def new
    @parent = Parent.new
  end

  def show # no longer used
    @parent = Parent.find(params[:id])
    @assigned_challenges = @parent.assigned_challenges.where("parent_id =?", @parent.id).where("accepted =?", false).where("rejected =?", false).where("completed =?", false).where("validated =?", false)
    @accepted_challenges = @parent.assigned_challenges.where("parent_id =?", @parent.id).where("accepted =?", true)
    @rejected_challenges = @parent.assigned_challenges.where("parent_id =?", @parent.id).where("rejected =?", true)
    @completed_challenges = @parent.assigned_challenges.where("parent_id =?", @parent.id).where("completed =?", true)
    @validated_challenges = @parent.assigned_challenges.where("parent_id =?", @parent.id).where("validated =?", true)
    @enabled_rewards = @parent.enabled_rewards.where("parent_id =?", @parent.id)
  end

  def dash
    @parent = current_user
    @children = @parent.children
    @completed_challenges = @parent.assigned_challenges.where("parent_id =?", @parent.id).where("completed =?", true)

    respond_to do |format|
      format.html
      format.json
    end
  end

  def index
    @parents = Parent.paginate(page: params[:page])
  end

  def update
    if @parent.update_attributes(params[:parent])
      flash[:success] = "Profile updated!"
      sign_in @parent
      redirect_to parent_dash_path
    else
      render 'edit'
    end
  end

  def create
    @parent = Parent.new(params[:parent])
    if @parent.save
      #Send welcome email to parent upon signup
      NotificationsMailer.welcome_email(@parent).deliver
      Mixpanel.simple_track('New parent account', {'distinct_id' => @parent.id}) # need reload?

      sign_in @parent
      flash[:success] = "Welcome to HealthMonster! You have successfully created your account"
      redirect_to parent_dash_path
    else
      render 'new'
    end
  end

  def destroy
    Parent.find(params[:id]).destroy
    flash[:success] = "Parent destroyed"
    redirect_to parents_url
  end

  private

    def signed_in_parent
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_parent
      @parent = Parent.find(params[:id])
      redirect_to(root_path) unless current_user?(@parent)
    end

    def admin_parent
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/parents_helper.rb
module ParentsHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(parent, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(parent.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: parent.name, class: "gravatar")
  end
end

app/views/parents/_challenge_validation.html.erb
<span class="par_mod_header">Challenge Validation</span>
<hr color="#e99723" align="left" width="95%"/>
<div align="center">
  <table width="100%" border="0" cellspacing="10" cellpadding="0">
    <% for completed_challenge in @completed_challenges do %>
      <tr>
        <td align="left">
          <b><%= completed_challenge.child.username %>: </b>
          <%= completed_challenge.challenge.name %>
        </td>
        <td>
          <%= form_for completed_challenge, :method => "put" do |f| %>
            <%= f.hidden_field :validated, value: true %>
            <%= f.hidden_field :completed, value: false %>
            <%= f.hidden_field :accepted, value: false %>
            <%= image_submit_tag("check.png", name: "commit", alt: "validate", size: "15x16") %>
          <% end %>
        </td>
        <td>
          <%= form_for completed_challenge, :method => "put" do |f| %>
            <%= f.hidden_field :validated, value: false %>
            <%= f.hidden_field :completed, value: false %>
            <%= f.hidden_field :accepted, value: true %>
            <%= image_submit_tag("x.png", name: "decline", alt: "decline", size: "17x17") %>
          <% end %>
        </td>
        <!--<td><%= image_tag("x.png", alt: "decline", size: "17x17") %></td>-->
      </tr>
    <% end %>
  </table>
  <!--<p><%= image_tag("navarrow_left.jpg", alt: "previous", size: "21x35") %><%= image_tag("navarrow_right.jpg", alt: "next", size: "21x35") %></p>-->
  <%= image_tag("spacer.gif") %>
</div>

app/views/parents/_create_new_challenge.html.erb
<tr select-task="create_new_challenge">
  <td>
    <div align="center">
      <%= image_tag("linkarrow.png", 
        ng_show: "selected.task != 'create_new_challenge'", 
        alt: "click", size: "12x10", border: "0") %>
      <%= image_tag("linkarrow_down.png", 
        ng_show: "selected.task == 'create_new_challenge'", 
        alt: "form", size: "12x10", border: "0") %>
    </div>
  </td>
  <td>Create new challenge</td>
</tr>
<tr ng-show="selected.task == 'create_new_challenge'">
  <td>
    <%= image_tag("spacer.gif") %>
  </td>
  <td>
    <div ng-show="challenge_errors.length != 0" class="alert alert-error">
      <strong>Errors</strong>
      <ul>
        <li ng-repeat="error in challenge_errors">
          {{error}}
        </li>
      </ul>
    </div>

    <table>
      <tr><td>name:</td><td><input ng-model="challenge.name"></td></tr>
      <tr><td>description: </td><td><input ng-model="challenge.description"></td></tr>
      <tr><td>points (9-999): </td><td><input ng-model="assigned_challenge.points"></td></tr>
      <tr>
        <td>category:</td>
        <td>
          <select ng-model="challenge.category_id">
            <option ng-repeat="category in categories" value="{{category.id}}">{{category.name}}</option>
          </select>
        </td>
      </tr>
      <tr><td>public:</td><td><input type="checkbox" ng-model="challenge.public"></td></tr>
      <tr>
        <td colspan="2">
          <div align="center">
            <button ng-click="createAssignedChallenge()">Assign</button>
          </div>
        </td>
      </tr>
    </table>
  </td>
</tr>

app/views/parents/_create_new_reward.html.erb
<tr select-task="create_new_reward">
  <td>
    <div align="center">
      <%= image_tag("linkarrow.png", 
        ng_show: "selected.task != 'create_new_reward'", 
        alt: "click", size: "12x10", border: "0") %>
      <%= image_tag("linkarrow_down.png", 
        ng_show: "selected.task == 'create_new_reward'", 
        alt: "form", size: "12x10", border: "0") %>
    </div>
  </td>
  <td>Create new reward</td>
</tr>
<tr ng-show="selected.task == 'create_new_reward'">
  <td>
    <%= image_tag("spacer.gif") %>
  </td>
  <td>
    <div ng-show="reward_errors.length != 0" class="alert alert-error">
      <strong>Errors</strong>
      <ul>
        <li ng-repeat="error in reward_errors">
          {{error}}
        </li>
      </ul>
    </div>

    <table>
      <tr><td>name:</td><td><input ng-model="reward.name"></td></tr>
      <tr><td>description:</td><td><input ng-model="reward.description"></td></tr>
      <tr><td>points:</td><td><input ng-model="enabled_reward.points"></td></tr>
      <tr><td>public:</td><td><input type="checkbox" ng-model="reward.public"></td></tr>
      <tr>
        <td colspan="2">
          <div align="center">
            <button ng-click="createEnabledReward()">Enable</button>
          </div>
        </td>
      </tr>
    </table>
  </td>
</tr>

app/views/parents/_offer_reward.html.erb
<br/>
<%= image_tag("spacer.gif") %>
<span class="par_mod_header">Offer Reward</span>
<hr color="#e99723" align="left" width="95%"/>
<table width="86%" border="0" align="center" cellpadding="0" cellspacing="10">
  <%= render 'parents/create_new_reward' %>
  <tr>
    <td>
      <div align="center">
        <%= link_to(image_tag("linkarrow.png", alt: "click", size: "12x10", border: "0"), rewards_community_pool_path) %>
      </div>
    </td>
    <td>
      <%= link_to("Search community rewards for ideas", rewards_community_pool_path) %>
    </td>
  </tr>
  <tr>
    <td>
      <div align="center">
        <%= link_to(image_tag("HMGold.png", alt: "click", size: "19x23", border: "0"), '#') %>
      </div>
    </td>
    <td class="hmgold_grey">Create repeating reward</td>
  </tr>
  <tr>
    <td>
      <div align="center">
        <%= link_to(image_tag("HMGold.png", alt: "click", size: "19x23", border: "0"), '#') %>
      </div>
    </td>
    <td class="hmgold_grey">HealthMonster Recommends</td>
  </tr>
</table>

app/views/parents/_parent.html.erb
<li>
  <%= gravatar_for parent, size: 52 %>
  <%= link_to parent.name, parent %>
    <% if current_user.admin? && !current_user?(parent) %>
    | <%= link_to "delete parent", parent, method: :delete,
                                  data: { confirm: "You sure you want to delete parent?" } %>
  <% end %>
</li>

app/views/parents/_select_player.html.erb
<span class="par_mod_header">Select Player</span>
<hr color="#e99723" align="left" width="95%"/>
<table width="90%" border="0" align="center" cellspacing="10" cellpadding="0">
  <tr ng-repeat="child in children" select-child={{child}}>
    <td>
      <table width="86%" border="0" align="center" cellpadding="0" cellspacing="10">
        <tr>
          <td>
            <div align="center">
              <%= image_tag("linkarrow.png", alt: "child", size: "12x10", border: "0") %>
            </div>
          </td>
          <td width="90%">
            <div>{{child.username}}</div>
          </td>
          <td>
            <a ng-href="/children/{{child.id}}">stats</a>
          </td>
          <td width="15%">&nbsp;</td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<%= image_tag("spacer.gif") %>

app/views/parents/_set_new_challenge.html.erb
<br/>
<span class="par_mod_header">Set New Challenge</span>
<hr color="#e99723" align="left" width="90%"/>
<table width="86%" border="0" align="center" cellpadding="0" cellspacing="10">
  <%= render 'parents/create_new_challenge' %>
  <tr>
    <td>
      <div align="center">
        <%= link_to(image_tag("linkarrow.png", alt: "click", size: "12x10", border: "0"), challenges_community_pool_path) %>
      </div>
    </td>
    <td>
      <%= link_to("Search community challenges for ideas", challenges_community_pool_path) %>
    </td>
  </tr>
  <tr>
    <td>
      <div align="center">
        <%= link_to(image_tag("HMGold.png", alt: "click", size: "19x23", border: "0"), '#') %>
      </div>
    </td>
    <td class="hmgold_grey">Create repeating challenge</td>
  </tr>
  <tr>
    <td>
      <div align="center">
        <%= link_to(image_tag("HMGold.png", alt: "click", size: "19x23", border: "0"), '#') %>
      </div>
    </td>
    <td class="hmgold_grey">HealthMonster Recommends</td>
  </tr>
</table>

app/views/parents/dash.html.erb
<div ng-app="healthmonster" id="par_content">
  <div ng-controller="DashCtrl">
    <div ng-show="challenge_success" class="alert alert-success">
      {{challenge_success}}
    </div>
    <div ng-show="reward_success" class="alert alert-success">
      {{reward_success}}
    </div>
    <p align="center">
      <%= image_tag("pardash/Dashboard.png", size: "872x28", alt: "Action Items") %>
    </p>
    <div align="center">
      <br/>
      <table width="880" border="0" cellspacing="10" cellpadding="10" >
        <tr>
          <td width="420"  align="left" valign="top">
            <%= render 'parents/select_player' %>
          </td>
          <td width="398"  align="left" valign="top">
            <%= render 'parents/challenge_validation' %>
          </td>
        </tr>
        <tr>
          <td width="420" align="left" valign="top">
            <%= render 'parents/set_new_challenge' %>
          </td>
          <td align="left" valign="top">
            <%= render 'parents/offer_reward' %>
          </td>
        </tr>
      </table>
    </div>
    <p align="center">&nbsp;</p>
  </div>
</div>
<!--end #feature-->

<!--end #content-->

app/views/parents/edit.html.erb
<div id="par_content">
  <div id="avatarbase_contact">
    <div id="right_avatar_acct">
      <%= image_tag("avatars/techguy_lt.png", :size => "267x355") %>
    </div>
  </div><!--end #avatarbase-->


  <p align="center">
    <%= image_tag("AccountSettings_01.png", :size => "873x28") %></p>
<br />
<%= form_for(@parent) do |f| %>
<%= render 'shared/error_messages' %>
<div align="center">
<table width="auto" border="0" cellspacing="10" cellpadding="0" id="acct_tab">
  <tr>
    <td width="15%"><div align="right">
      <%= f.label :name %>
    </td>
    <td width="85%"><div align="left">
      <%= f.text_field :name %>
    </td>
  </tr>
  <tr>
    <td width="15%"><div align="right">
      <%= f.label :email %>
    </td>
    <td width="85%"><div align="left">
      <%= f.text_field :email %>
    </td>
  </tr>
  <tr>
    <td width="15%"><div align="right">
      <%= f.label :password %>
    </td>
    <td width="85%"><div align="left">
      <%= f.password_field :password %>
    </td>
  </tr>
  <tr>
    <td width="15%"><div align="right">
     <%= f.label :password_confirmation, "Confirm Password" %>
    </td>
    <td width="85%"><div align="left">
     <%= f.password_field :password_confirmation %>
    </td>
  </tr>
  <tr>
    <td width="15%" align="right" valign="top">Children
    </td>
    <td>
      <% @parent.children.each do |child| %>
      <%= child.username %>
      <b><%= link_to "Edit", "/children/#{child.id}/edit" %></b>
      <b><%= link_to "Delete", child, method: :delete,
                                  data: { confirm: "Are you sure you want to permanently delete this child and all of its data? This operation is irreversible." } %></b>
      <br>
      <% end %>
    </td>
  </tr>
  <tr>
    <td>
    </td>
    <td>
      <h4><%= link_to "Sign up a child", new_child_path %></h4>
    </td>
  </tr>
  <tr>
    <td>
    </td>
    <td>
      <%= f.submit "Save changes", class: "btn btnlarge btn-primary" %>
    </td>
  </tr>
</table>


<% end %>
</div>

  <p align="center">&nbsp;</p>
  <p align="center">&nbsp;</p>
  </div>
<!--end #feature-->

 <!--end #content-->



</div> <!--end #wrap-->

app/views/parents/edit_old.html.erb
<% provide(:title, "Edit parent") %> 
<h1>Update your profile</h1>

<div align="center">
   <%= form_for(@parent) do |f| %>
     <%= render 'shared/error_messages' %>
     <%= f.label :name %>
     <%= f.text_field :name %>
     <br>
     <%= f.label :email %>
     <%= f.text_field :email %>
     <br>
     <%= f.label :password %>
     <%= f.password_field :password %>
     <br>
     <%= f.label :password_confirmation, "Confirm Password" %>
     <%= f.password_field :password_confirmation %>
     <br>
     <%= f.submit "Save changes", class: "btn btnlarge btn-primary" %>
   <% end %>
   <br>
   <h3><%= link_to "Sign up a child", new_child_path %></h3>
   <br>
   <%= gravatar_for @parent %>
   <a href="http://gravatar.com/emails">change</a>
</div>

app/views/parents/index.html.erb
<% provide(:title, 'All parents') %>
<h1>All parents</h1>

<%= will_paginate %>

<ul class="parents">
  <%= render @parents %>
</ul>

<%= will_paginate %>

app/views/parents/new.html.erb
<% provide(:title, 'Sign up') %>

<div id="content">

<div id="avatarbase_reg">
  <div id="left_img_reg"><%= image_tag("avatars/lion_lt.png", alt: "Lion") %></div>
</div><!--end #avatarbase-->

<div id="forty_left" class="align_lt">
  <h1>Register here to join HealthMonster:</h1>
  <p>&nbsp;</p>
  <div align="center" >
    <%= form_for(@parent) do |f| %>
      <%= render 'shared/error_messages' %>

      <table width="auto" border="0" cellspacing="12" cellpadding="0" id="reg_table">
        <tr class="rowheight">
          <td width="135" height="40" class="labels">Name: </td>
          <td width="278" height="40" class="fields"><%= f.text_field :name, size: "40", maxlength: "40" %></td>
        </tr>
        <tr class="rowheight">
          <td class="labels" height="40">E-mail:</td>
          <td class="fields"><%= f.text_field :email, size: "40" %></td>
        </tr>
        <tr class="rowheight">
          <td class="labels" height="40">Password:</td>
          <td class="fields"><%= f.password_field :password, size: "40" %></td>
        </tr>
        <tr class="rowheight">
          <td width="135" height= "40" class="labels">Confirm Password:</td>
          <td class="fields"><%= f.password_field :password_confirmation, size: "40" %></td>
        </tr>
        <tr>
          <td height="68" colspan="5" class="reg_inst"><div align="center">
            <p>
              <%= image_submit_tag("HM-Submit-A.png", name: "commit", alt: "Join HealthMonster") %>
            </p>
            <p>&nbsp;  </p>
          </div></td>
        </tr>
      </table>
    <% end %>

  <!--end #forty_left-->
  <%= image_tag("spacer.gif", height: "100px") %></p>
 <p>&nbsp;</p>
 <p>&nbsp;</p>
 <p>&nbsp; </p>
</div> <!--end #content-->

app/views/parents/show.html.erb
<% provide(:title, @parent.name) %>
<h1>
  <%= gravatar_for @parent %>
  <%= @parent.name %>
</h1>

<h4>Assigned Challenges</h4>
<ol>
  <% @assigned_challenges.each do |assigned_challenge| %>
    <li><b>Challenge: </b><%= assigned_challenge.challenge.name %><b> Child: </b> <%= assigned_challenge.child.username %><b> Category: </b><%= assigned_challenge.category.name %>
    </li>
  <% end %>
</ol>
<br>
<h4>Accepted Challenges</h4>
<ol>
  <% @accepted_challenges.each do |accepted_challenge| %>
    <li><b>Challenge: </b><%= accepted_challenge.challenge.name %><b> Child: </b> <%= accepted_challenge.child.username %><b> Category: </b><%= accepted_challenge.category %>
    </li>
  <% end %>
</ol>
<br>
<h4>Completed Challenges</h4>
<ol>
  <% @completed_challenges.each do |completed_challenge| %>
    <li><b>Challenge: </b><%= completed_challenge.challenge.name %><b> Child: </b> <%= completed_challenge.child.username %><b> Category: </b><%= completed_challenge.category.name %>
      <%= form_for completed_challenge, :method => "put" do |f| %>

        <%= f.hidden_field :validated, value: true %>
        <%= f.hidden_field :completed, value: false %>
        <%= f.hidden_field :accepted, value: false %>

        <%= f.submit "Validate" %>
      <% end %>
    </li>
  <% end %>
</ol>
<br>
<h4>Validated Challenges</h4>
<ol>
  <% @validated_challenges.each do |validated_challenge| %>
    <li><b>Challenge: </b><%= validated_challenge.challenge.name %><b> Child: </b> <%= validated_challenge.child.username %><b> Category: </b><%= validated_challenge.category.name %>
    </li>
  <% end %>
</ol>
<br>
<h4>Rejected Challenges</h4>
<ol>
  <% @rejected_challenges.each do |rejected_challenge| %>
    <li><b>Challenge: </b><%= rejected_challenge.challenge.name %><b> Child: </b> <%= rejected_challenge.child.username %><b> Category: </b><%= rejected_challenge.category.name %>
    </li>
  <% end %>
</ol>
<br>
<h4>Enabled Rewards</h4>
<ol>
  <% @enabled_rewards.each do |enabled_reward| %>
    <li><b>Reward: </b><%= enabled_reward.reward.name %><b> Child: </b> <%= enabled_reward.child.username %>
    </li>
  <% end %>
</ol>