config/routes.rb
Hm::Application.routes.draw do
  resources :parents
  resources :sessions, only: [:new, :create, :destroy]
  resources :challenges, controller: "resources", type: "Challenge"
  resources :rewards, controller: "resources", type: "Reward"
  resources :children
  resources :assigned_challenges
  resources :enabled_rewards
  resources :messages
  resources :categories, only: [:index]

  root to: 'static_pages#home'

  match '/signup',   to: 'parents#new'
  match '/signin',   to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy', via: :delete

  match '/about',                   to: 'static_pages#about'
  match '/legal',                   to: 'static_pages#legal'
  match '/partners',                to: 'static_pages#partners'
  match '/how_it_works',            to: 'static_pages#how_it_works'
  match '/parent_child_connection', to: 'static_pages#parent_child_connection'
  match '/community',               to: 'static_pages#community'
  match '/glossary_of_terms',       to: 'static_pages#glossary_of_terms'
  match '/challenge_categories',    to: 'static_pages#challenge_categories'
  
  match '/challenges_your',           to: 'challenges#your'
  match '/challenges_community_pool', to: 'challenges#community_pool'
  match '/rewards_your',              to: 'rewards#your'
  match '/rewards_community_pool',    to: 'rewards#community_pool'
  match '/children_your',             to: 'children#your'
  match '/parent_dash',               to: 'parents#dash'
  match '/completed_challenges',      to: 'assigned_challenges#completed'
  match '/child_dash',                to: 'children#dash'

  match '/contact' => 'contact#new', :as => 'contact', :via => :get
  match '/contact' => 'contact#create', :as => 'contact', :via => :post

  match '/report_abuse' => 'report_abuse#new', :as => 'report_abuse', :via => :get
  match '/report_abuse' => 'report_abuse#create', :as => 'report_abuse', :via => :post

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div id="foot">
    <div align="center">
      <table width="879" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="233">
            <div align="left">
              <%= link_to "about", about_path %> | <%= link_to "contact", contact_path %> | <%= link_to "legal", legal_path %> | <%= link_to "partners", partners_path %><br/>
              ©HealthMonster 2011
            </div>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/layouts/_google_analytics.html.erb
<!--Beginning of Google Analytics-->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-24991358-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<!--End of Google Analytics-->

app/views/layouts/_header.html.erb
<div id="header">
  <div id="logo">
    <%= link_to image_tag("HM_logo250w.png", alt: " HealthMonster", size: "250x91", class: "logo"),  root_path %>
  
    <div id="signreg">
      <% if signed_in? %>
        <% if signed_in_as_parent? %>
          <a href="#"><%= image_tag("HMGold.png", alt: "HealthMonster Gold", size: "19x23", border: "0") %></a> Join HealthMonster Gold | 
        <% end %>
        <%= link_to "sign out", signout_path, method: "delete" %>
      <% else %>
        <%= link_to "sign in |", signin_path %>
        <%= link_to "register", signup_path %>
      <% end %>
    </div>

    <div id="powerfields">
      <table width="275px" border="0" cellpadding="0"   cellspacing="2">
        <%= form_for(:session, url: sessions_path) do |f| %>
          <tr>
            <td width="80" class="fields"/>
              <% unless signed_in? %>
                  <%= f.text_field :email_username, id: "textfield", placeholder: "Username" %>
                </td>
                <td width="80" class="fields"/>
                  <%= f.password_field :password, id: "textfield2", placeholder: "Password" %>
                </td>
                <td>
                  <%= image_submit_tag("power.png", name: "commit", alt: "Submit") %>
                </td>
              </tr>
              <tr>
              <% else %>
                <%= image_tag("spacer.gif") %>
              <% end %>
            </td>
          </tr>
      </form>
    <% end %>
      </table>
    </div>

    <!--end #powerfields-->
  
    <div id="headernav">
      <% if signed_in? %>
        <% if signed_in_as_parent? %>
          <%= link_to "dashboard |", parent_dash_path %>
          <%= render 'layouts/header_parent' %>
        <% elsif signed_in_as_child? %>
          <%= link_to "dashboard |", child_dash_path %>
          <%= render 'layouts/header_child' %>
        <% end %>
      <% else %>
        <ul id='menu'>
          <li>
            <%= link_to "home |", root_path %>
          </li>
          <li>
            <%= link_to "about |", about_path %>
            <ul class="sub-menu">
              <li>
                <%= link_to "parent-child connection", parent_child_connection_path %>
              </li>
              <li>
                <%= link_to "community", community_path %>
              </li>
            </ul>
          </li>
          <li>
            <%= link_to "how it works |", how_it_works_path %>
            <ul class="sub-menu">
              <li>
                <%= link_to "glossary of terms", glossary_of_terms_path %>
              </li>
              <li>
                <%= link_to "challenge categories", challenge_categories_path %>
              </li>
            </ul>
          </li>
          <li>
          <%= link_to "contact", contact_path %>
          </li>
        </ul>
      <% end %>
    </div> <!--End #headernav-->
  </div> <!--End #logo -->
  
  <div id="horizdiv">
    <%= image_tag("horiz_div958w.png") %>
  </div> <!--end #horizdiv-->
</div> <!--end #header-->

app/views/layouts/_header_child.html.erb
<%= link_to "avatar settings", edit_child_path(current_user) %>
<!--<%= link_to "message center", current_user %>-->

app/views/layouts/_header_parent.html.erb
<%= link_to "account settings |", edit_parent_path(current_user) %>
<%= link_to "search challenges |", challenges_community_pool_path %>
<%= link_to "search rewards", rewards_community_pool_path %>
<!--<%= link_to "message center", current_user %>-->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=full_title(yield(:title))%></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= render 'layouts/google_analytics' %>  
  </head>
  <body>
    <div class="wrap">
      <%= render 'layouts/header' %>
      <!--<div class="container">-->
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>
        <%= yield %>
    </div><!--end #wrap-->
    <div id="spacer" ></div> <!--end #spacer-->
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
        <% YAML::ENGINE.yamler= 'syck' %>
        <%= debug(@enabled_reward) if @enabled_rewar&&     Rails.env.development? %>
        <%= debug(@enabled_reward.child) if @enabled_reward && Rails.env.development? %>
    </div>
  </body>
</html>